### ISSUE TITLE
add a package.json

### ISSUE THREAD

**Issue by btopro** [RolandDreger/web-components#2]
This helps w/ sustainable development using package managers like yarn / npm / etc. While I know this has 0 dependencies, even just adding `name` (https://github.com/elmsln/lrnwebcomponents/blob/master/elements/air-horn/package.json#L2 ) will help w/ install. Right now it goes in `node_modules/web-components` which isn't name spaced at all.

**Comment by RolandDreger** [comment]
I have added the package.json files. Thanks for the hint. Hope it works, otherwise please let me know.

**Comment by btopro** [comment]
`"homepage": "https://github.com/RolandDreger/web-components",`

was recommended by validator I looked at but is just a recommendation; looks good to me
