### ISSUE TITLE
demo in readme goes no where

### ISSUE THREAD

**Issue by btopro** [RolandDreger/web-components#3]
https://github.com/RolandDreger/web-components/blob/master/foot-note/README.md#demo

**Comment by RolandDreger** [comment]
When I click on the link, I get to the demo page. But I did a server update this afternoon, probably that's why the link did not work!?

**Comment by btopro** [comment]
```
Forbidden
You don't have permission to access /components/foot-note/index.html on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.
```

**Comment by RolandDreger** [comment]
I just tried it with another computer and another browser, everything works here. Just to be sure, you mean this link:
<img width="1144" alt="Bildschirmfoto 2020-09-21 um 21 35 32" src="https://user-images.githubusercontent.com/19747449/93813054-ce7c6c80-fc52-11ea-9621-5f27412df275.png">

**Comment by btopro** [comment]
https://www.rolanddreger.net/components/foot-note/index.html -- Yeah if I click that link I get the error I copy and pasted of a forbidden error. Are you maybe logged into the server w/ some credential that makes it available?

https://downforeveryoneorjustme.com/rolanddreger.net?proto=https&www=1

**Comment by RolandDreger** [comment]
I have now set a link to a GitHub page :)

**Comment by btopro** [comment]
nice!
